### ISSUE TITLE
Web server not sending intermediate SSL certificates

### ISSUE THREAD

**Issue by markusdosch** [TUM-Dev/TUM.sexy#102]
Following up on #96 - I now dug into the issue a bit deeper (as I am receiving an SSL certiciate error on macOS as well, not just iOS). I It really seems to be connected to a cached certificate - but the root issue is that **the webserver is not sending intermediate certificates**. 

So this is an issue that should be fixed on the tum.sexy web server. 

The issue is quite well explained here: https://community.letsencrypt.org/t/my-iphone-seems-to-used-a-cached-version-of-the-old-expired-r3/160931/2

> [..] but a likely cause is because your server doesn't send the intermediate certificates. This causes clients to fetch them themselves and may lead to what you're seeing.

You can verify the issue e.g. on https://www.sslchecker.com/sslchecker (see screenshot):
![image](https://user-images.githubusercontent.com/757612/139553730-5c77de32-e735-4a8e-9dd4-b613dadbfe06.png)

You should also be able to verify the issue by running `openssl s_client -connect tum.sexy:443` (currently returns `unable to verify the first certificate`, at least for my computer).

Which web server & config are you using? Happy to assist 😊

**Comment by kordianbruck** [comment]
ugh, yeah, that actually makes a lot of sense. Thanks for digging deeper :)

We are using traefik as an ingress controller but with a custom certificate setup in order to support wildcard subdomains. I would've assumed that the `acme.sh` certificate client does the right thing here to also put the intermediate into the same cert file, but maybe I need to append the two together. I'll have a look tomorrow.

**Comment by kordianbruck** [comment]
![image](https://user-images.githubusercontent.com/298860/140429197-550d4647-2470-4de0-8f42-7ccaecb8890d.png)

Fixed now, can you please confirm this is now working for you?

**Comment by markusdosch** [comment]
Yeah, it's working, awesome! Thanks for the fast resolution! 🥳
